"""Causal-factor portfolio, graph, specification-error, and protocol methods.

This package implements externally published Causal Factor Analysis equations
and graphical identification criteria together with the seven-stage research
protocol, without importing the broader causal or portfolio-optimization
namespaces.
"""

from .factor_mirage import (
    ColliderCoefficients,
    ColliderDiagnostics,
    StrategyPerformance,
    collider_factor_return,
    collider_forecast_return,
    collider_model_diagnostics,
    collider_overcontrolled_coefficients,
    confounder_factor_return,
    confounder_forecast_return,
    confounder_undercontrolled_coefficient,
)
from .graph_identification import (
    BackdoorAdjustmentEvidence,
    CausalDAG,
    DSeparationEvidence,
    FrontdoorAdjustmentEvidence,
    InstrumentEvidence,
    NodeRoleEvidence,
    PathEvidence,
    causal_role_evidence,
    check_backdoor_adjustment_set,
    check_frontdoor_adjustment_set,
    check_instrument,
    d_separation,
    minimal_backdoor_adjustment_sets,
    minimal_frontdoor_adjustment_sets,
)
from .optimizer import minimum_variance_factor_weights
from .protocol import (
    BacktestStage,
    CausalAdjustmentSetStage,
    CausalDiscoveryStage,
    CausalExplanatoryAndPredictivePowerStage,
    CausalFactorProtocolReport,
    CausalPortfolioConstructionStage,
    EventHorizon,
    FoldEvidence,
    MultipleTestingAdjustmentsStage,
    ValidationEvidence,
    VariableSelectionStage,
    validate_causal_factor_protocol,
)
from .specification_diagnostics import (
    PopulationRegressionDiagnostics,
    RegressionDiagnostics,
    SpecificationExperimentResult,
    SpecificationPopulationResult,
    collider_population_diagnostics,
    collider_specification_experiment,
    confounded_mediator_population_diagnostics,
    confounded_mediator_specification_experiment,
    fork_population_diagnostics,
    fork_specification_experiment,
)
from .treatment_effects import (
    DifferenceInDifferencesEstimate,
    TreatmentEffectDecomposition,
    average_treatment_effect,
    backdoor_adjusted_average_treatment_effect,
    backdoor_adjusted_expectation,
    difference_in_differences,
    frontdoor_adjusted_probability,
    linear_instrumental_variable_effect,
    randomized_mean_difference,
    treatment_effect_decomposition,
)

__all__ = [
    "BackdoorAdjustmentEvidence",
    "BacktestStage",
    "CausalDAG",
    "CausalAdjustmentSetStage",
    "ColliderCoefficients",
    "ColliderDiagnostics",
    "CausalDiscoveryStage",
    "CausalExplanatoryAndPredictivePowerStage",
    "CausalFactorProtocolReport",
    "CausalPortfolioConstructionStage",
    "DSeparationEvidence",
    "DifferenceInDifferencesEstimate",
    "EventHorizon",
    "FoldEvidence",
    "FrontdoorAdjustmentEvidence",
    "InstrumentEvidence",
    "MultipleTestingAdjustmentsStage",
    "NodeRoleEvidence",
    "PathEvidence",
    "PopulationRegressionDiagnostics",
    "RegressionDiagnostics",
    "SpecificationExperimentResult",
    "SpecificationPopulationResult",
    "StrategyPerformance",
    "TreatmentEffectDecomposition",
    "ValidationEvidence",
    "VariableSelectionStage",
    "average_treatment_effect",
    "backdoor_adjusted_average_treatment_effect",
    "backdoor_adjusted_expectation",
    "causal_role_evidence",
    "check_backdoor_adjustment_set",
    "check_frontdoor_adjustment_set",
    "check_instrument",
    "collider_factor_return",
    "collider_forecast_return",
    "collider_model_diagnostics",
    "collider_overcontrolled_coefficients",
    "collider_population_diagnostics",
    "collider_specification_experiment",
    "confounded_mediator_population_diagnostics",
    "confounded_mediator_specification_experiment",
    "confounder_factor_return",
    "confounder_forecast_return",
    "confounder_undercontrolled_coefficient",
    "d_separation",
    "difference_in_differences",
    "fork_population_diagnostics",
    "fork_specification_experiment",
    "frontdoor_adjusted_probability",
    "linear_instrumental_variable_effect",
    "minimal_backdoor_adjustment_sets",
    "minimal_frontdoor_adjustment_sets",
    "minimum_variance_factor_weights",
    "randomized_mean_difference",
    "treatment_effect_decomposition",
    "validate_causal_factor_protocol",
]
